# WSL2: in ~/.docker/config.json, rename key "credsStore" to "credStore" to prevent error (https://github.com/docker/buildx/issues/415)

# docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:8.0.31-debian -p localhost:8080:8080
# docker exec -it mysql mysql -u root -p
# docker build -t am4bot_repr .
# docker run -it am4bot_repr

FROM debian:bullseye-slim

RUN apt-get update \
    && apt-get install -y \
        build-essential software-properties-common wget \
        libboost-all-dev unixodbc unixodbc-dev \
        python3-pip python3-dev \
    # install MySQL 8.0.31 ODBC connector, core client
    && wget -O ccp.deb https://repo.mysql.com/apt/debian/pool/mysql-8.0/m/mysql-community/mysql-community-client-plugins_8.0.31-1debian11_amd64.deb \
    && wget -O odbc.deb https://repo.mysql.com/apt/debian/pool/mysql-tools/m/mysql-connector-odbc/mysql-connector-odbc_8.0.31-1debian11_amd64.deb \
    && wget -O ccc.deb https://repo.mysql.com/apt/debian/pool/mysql-8.0/m/mysql-community/mysql-community-client-core_8.0.31-1debian11_amd64.deb \
    && dpkg -i ccp.deb odbc.deb ccc.deb \
    && rm ccp.deb odbc.deb ccc.deb \
    # register DSN
    && myodbc-installer -s -a -n "test" -t "Driver=MySQL ODBC 8.0 Unicode Driver;Server=$MYSQL_HOST;User=$MYSQL_USER;Password=$MYSQL_PASSWORD;Database=$MYSQL_DATABASE;" \
    && pip3 install --no-cache-dir numpy==1.23.5 pyarrow==9.0.0 \
    && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
    && CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc==4.5.5 \
    # cleanup
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# /usr/bin/myodbc-installer
# odbcinst -j



# install apt config
# apt-get install debconf-utils
# wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb \
#     && echo "mysql-apt-config mysql-apt-config/select-product select Ok" | debconf-set-selections \
#     && echo "mysql-apt-config mysql-apt-config/select-server select mysql-8.0" | debconf-set-selections \
#     && echo "mysql-apt-config mysql-apt-config/select-tools select Enabled" | debconf-set-selections \
#     && dpkg -i mysql-apt-config_0.8.24-1_all.deb \
#     && apt-get update \