# attempt to reproduce pyodbc/turbodbc mysql issues when pandas is imported.
# TODO: use postgres/sqlite


# docker build -t am4bot_repr .
# docker run -it am4bot_repr

FROM debian:bullseye-slim

RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb &&
    dpkg -i mysql-apt-config_0.8.24-1_all.deb &&
    apt-get update &&
    apt-get install -y mysql-server &&
    systemctl status mysql.service

# RUN apt-get update
# RUN export DEBIAN_FRONTEND=noninteractive
# RUN apt-get -y install build-essential software-properties-common
# RUN apt-get -y install python3 python3-pip python3-pip python3-venv python3-dev
# RUN apt-get -y install default-libmysqlclient-dev libboost-all-dev unixodbc unixodbc-dev

# RUN CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc
# RUN python3 -c "import turbodbc.cursor as c; print(c._has_arrow_support(), c._has_numpy_support())

# FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal

# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#      && apt-get -y install --no-install-recommends \
#         build-essential \
#         default-libmysqlclient-dev \
#         libpython3-dev \
#         libboost-all-dev \
#         python3 \
#         python3-pip \
#         python3-wheel \
#         python3-dev \
#         python3-venv \
#         software-properties-common \
#         unixodbc \
#         unixodbc-dev \
#     && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
#     && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
#     && apt-get update && apt-get -y upgrade \
#     && wget -qO- --no-check-certificate https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
#     && add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)" \
#     && apt-get update && apt-get -y upgrade \
#     && apt-get -y install --no-install-recommends mssql-server \
#     && ACCEPT_EULA=Y apt-get install --no-install-recommends -y msodbcsql17 \
#     && ACCEPT_EULA=Y apt-get install --no-install-recommends -y mssql-tools \
#     && apt-get update && apt-get -y upgrade

# # Change to Project Base Folder
# WORKDIR /workspaces/project_name

# ARG VIRTUAL_ENV="/opt/venv"
# ENV VIRTUAL_ENV $VIRTUAL_ENV
# RUN python3 -m venv ${VIRTUAL_ENV}
# ENV PATH="$VIRTUAL_ENV/bin:$PATH"
# RUN . ${VIRTUAL_ENV}/bin/activate

# # Get requirements.txt file
# COPY requirements.txt .

# # Install Dependencies
# RUN pip3 install -U pip==22.0.4 setuptools==45.2.0 wheel==0.37.1 \
#     && pip3 install --no-cache-dir -r requirements.txt \
#     && python3 -c "import pyarrow; pyarrow.create_library_symlinks()" \
#     && CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" pip3 install --no-cache-dir turbodbc

# # Clean up
# RUN apt-get autoremove -y \
#     && apt-get clean -y \
#     && rm -rf /var/lib/apt/lists/*
